### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by weissri** [edurange/edurange-server#30]
add a button for users to reset their password

**Comment by thebareju** [comment]
I think we might need to change how password reset works so that users are sent a URL that resets their password, rather than resetting it immediately. That way a person can't reset someone else's a password only by knowing their email address.

It looks like Devise (the authentication system we use) has a module that helps with this.

**Comment by thebareju** [comment]
Done, check out the development server. Also, turns out this was on the production server, but was hidden behind the "sign in" link.

Note that the home page controller now redirects for the log in page, rather than having two separate log in pages for the home page and devise's log in page.
